[tool.isort]
known_first_party = ["django-tus"]
known_django = ["django"]
known_djangorestframework = ["rest_framework"]
sections = ["FUTURE", "STDLIB", "DJANGO", "DJANGORESTFRAMEWORK", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
profile = "black"
multi_line_output = 3
line_length = 120
skip_gitignore = true

[tool.black]
line_length = 120
target-version = ['py311']
include = '\.pyi?$'
